# Generated by Django 3.0.3 on 2020-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airticket_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
