# Generated by Django 3.0.3 on 2020-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airticket_booking', '0006_auto_20200512_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
